import './globals.css'
import { Work_Sans } from 'next/font/google'

const workSans = Work_Sans({
  weight: ['300', '500'],
  subsets: ['latin']
})

export const metadata = {
  title: 'Next Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`bg-gradient-to-tl from-black to-blackgr ${workSans.className}`}>
        <main
          className="xl:container mx-auto px-8 text-neutral-1">
          {children}
        </main>
      </body>
    </html>
  )
}
